import logging
import json
import asyncio
import typing
from pathlib import Path
import dataclasses

from src.data_services.vendors.eodhd import Eodhd
from data_services.utils.universe import Universe
from data_services.utils.log import logging_dict
from data_services.utils.generic import DataQuery
from data_services.vendors.vendor import MarketDataVendor

# Output locations
OUTPUT_BASE_DIR = Path(__file__).resolve().parents[2]
OUTPUT_BASE_DIR = Path(OUTPUT_BASE_DIR, "out")
OUTPUT_METADATA = Path(OUTPUT_BASE_DIR, "metadata")
OUTPUT_ETF_OHLCV = Path(OUTPUT_BASE_DIR, "etf/ohlcv")
OUTPUT_CRYPTO = Path(OUTPUT_BASE_DIR, "crypto")

OUTPUT_BASE_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_METADATA.mkdir(parents=True, exist_ok=True)
OUTPUT_ETF_OHLCV.mkdir(parents=True, exist_ok=True)
OUTPUT_CRYPTO.mkdir(parents=True, exist_ok=True)

# Initialize logger
logging.config.dictConfig(logging_dict)
_logger = logging.getLogger(__name__)


# -------------------------------------------------------------------------------------------------------------
# ETF DATA
# -------------------------------------------------------------------------------------------------------------
class EtfData:
    """Requests and load ETF data"""

    def __init__(self) -> None:
        self.__service = Eodhd()

    # @save_to_file
    async def _load_universe_async(self, query: DataQuery, universe: Universe | typing.Tuple):
        """
        Returns a list of historical Open-High-Low-Close-Volume (OHLCV) data
        for a defined universe, as specified in the global universe
        configuration file.
        """
        if isinstance(universe, typing.Tuple):
            _logger.debug("Loading custom universe parameters....")
            universe_name = universe[0]
            tickers = universe[1]
        else:
            _logger.debug("Loading universe parameters....")
            universe_name = universe.value[0]
            tickers = universe.value[2]

        _logger.info(f"Ohlcv retrieval for {universe_name}...")
        query = dataclasses.replace(query, tickers=tickers)
        ohlcv_data, _ = await self.__service.getOhlcvData(ohlcv_query=query)
        filepath_universe = f"{OUTPUT_ETF_OHLCV}/{universe_name}.h5"
        _logger.info(f"Retrieval done for {universe_name}!")
        return filepath_universe, ohlcv_data, universe_name

    def load_etf_universe(
        self, query: DataQuery, universe: Universe, save_file: bool = False
    ) -> typing.Tuple[typing.List[str], typing.List[typing.Dict]]:
        """loads a specific etf universe for a specific period"""

        if save_file:
            return asyncio.run(self._load_universe_async(query, universe=universe))
        else:
            load_func = self._load_universe_async.__wrapped__
            return asyncio.run(load_func(self, query, universe=universe))

    def load_all(self, query: DataQuery):
        """Loads all etfs data asynchronously for a specific period."""

        # ALL_ETF = (
        #     Universe.US_EQ_SECTOR.value[2]
        #     + Universe.US_EQ_INDEX.value[2]
        #     + Universe.EQ_DEV_COUNTRY.value[2]
        #     + Universe.EQ_EM_COUNTRY.value[2]
        #     + Universe.US_FI_ETF.value[2]
        #     + Universe.COMMO_ETF.value[2]
        # )
        ALL_ETF = [
            "GPC",
            "GILD",
            "GL",
            "GPN",
            "GS",
            "HAL",
            "HIG",
            "HAS",
            "HCA",
            "PEAK",
            "HSIC",
            "HSY",
            "HES",
            "HPE",
            "HLT",
            "HOLX",
            "HD",
            "HON",
            "HRL",
            "HST",
            "HWM",
            "HPQ",
            "HUBB",
            "HUM",
            "HBAN",
            "HII",
            "IBM",
            "IEX",
            "IDXX",
            "ITW",
            "ILMN",
            "INCY",
            "IR",
            "PODD",
            "INTC",
            "ICE",
            "IFF",
            "IP",
            "IPG",
            "INTU",
            "ISRG",
            "IVZ",
            "INVH",
            "IQV",
            "IRM",
            "JBHT",
            "JKHY",
            "J",
            "JNJ",
            "JCI",
            "JPM",
            "JNPR",
            "K",
            "MMM",
            "AOS",
            "ABT",
            "ABBV",
            "ACN",
            "ADM",
            "ADBE",
            "ADP",
            "AES",
            "AFL",
            "A",
            "ABNB",
            "APD",
            "AKAM",
            "ALK",
            "ALB",
            "ARE",
            "ALGN",
            "ALLE",
            "LNT",
            "ALL",
            "GOOGL",
            "GOOG",
            "MO",
            "AMZN",
            "AMCR",
            "AMD",
            "AEE",
            "AAL",
            "AEP",
            "AXP",
            "AIG",
            "AMT",
            "AWK",
            "AMP",
            "AME",
            "AMGN",
            "APH",
            "ADI",
            "ANSS",
            "AON",
            "APA",
            "AAPL",
            "AMAT",
            "APTV",
            "ACGL",
            "ANET",
            "AJG",
            "AIZ",
            "T",
            "ATO",
            "ADSK",
            "AZO",
            "AVB",
            "AVY",
            "AXON",
            "BKR",
            "BALL",
            "BAC",
            "BBWI",
            "BAX",
            "BDX",
            "WRB",
            "BRK.B",
            "BBY",
            "BIO",
            "TECH",
            "BIIB",
            "BLK",
            "BX",
            "BK",
            "BA",
            "BKNG",
            "BWA",
            "BXP",
            "BSX",
            "BMY",
            "AVGO",
            "BR",
            "BRO",
            "BF.B",
            "BG",
            "CHRW",
            "CDNS",
            "CZR",
            "CPT",
            "CPB",
            "COF",
            "CAH",
            "KMX",
            "CCL",
            "CARR",
            "CTLT",
            "CAT",
            "CBOE",
            "CBRE",
            "CDW",
            "CE",
            "COR",
            "CNC",
            "CNP",
            "CDAY",
            "CF",
            "CRL",
            "SCHW",
            "CHTR",
            "CVX",
            "CMG",
            "CB",
            "CHD",
            "CI",
            "CINF",
            "CTAS",
            "CSCO",
            "C",
            "CFG",
            "CLX",
            "CME",
            "CMS",
            "KO",
            "CTSH",
            "CL",
            "CMCSA",
            "CMA",
            "CAG",
            "COP",
            "ED",
            "STZ",
            "CEG",
            "COO",
            "CPRT",
            "GLW",
            "CTVA",
            "CSGP",
            "COST",
            "CTRA",
            "CCI",
            "CSX",
            "CMI",
            "CVS",
            "DHI",
            "DHR",
            "DRI",
            "DVA",
            "DE",
            "DAL",
            "XRAY",
            "DVN",
            "DXCM",
            "FANG",
            "DLR",
            "DFS",
            "DIS",
            "DG",
            "DLTR",
            "D",
            "DPZ",
            "DOV",
            "DOW",
            "DTE",
            "DUK",
            "DD",
            "EMN",
            "ETN",
            "EBAY",
            "ECL",
            "EIX",
            "EW",
            "EA",
            "ELV",
            "LLY",
            "EMR",
            "ENPH",
            "ETR",
            "EOG",
            "EPAM",
            "EQT",
            "EFX",
            "EQIX",
            "EQR",
            "ESS",
            "EL",
            "ETSY",
            "EG",
            "EVRG",
            "ES",
            "EXC",
            "EXPE",
            "EXPD",
            "EXR",
            "XOM",
            "FFIV",
            "FDS",
            "FICO",
            "FAST",
            "FRT",
            "FDX",
            "FITB",
            "FSLR",
            "FE",
            "FIS",
            "FI",
            "FLT",
            "FMC",
            "F",
            "FTNT",
            "FTV",
            "FOXA",
            "FOX",
            "BEN",
            "FCX",
            "GRMN",
            "IT",
            "GEHC",
            "GEN",
            "GNRC",
            "GD",
            "GE",
            "GIS",
            "GM",
            "KVUE",
            "KDP",
            "KEY",
            "KEYS",
            "KMB",
            "KIM",
            "KMI",
            "KLAC",
            "KHC",
            "KR",
            "LHX",
            "LH",
            "LRCX",
            "LW",
            "LVS",
            "LDOS",
            "LEN",
            "LIN",
            "LYV",
            "LKQ",
            "LMT",
            "L",
            "LOW",
            "LULU",
            "LYB",
            "MTB",
            "MRO",
            "MPC",
            "MKTX",
            "MAR",
            "MMC",
            "MLM",
            "MAS",
            "MA",
            "MTCH",
            "MKC",
            "MCD",
            "MCK",
            "MDT",
            "MRK",
            "META",
            "MET",
            "MTD",
            "MGM",
            "MCHP",
            "MU",
            "MSFT",
            "MAA",
            "MRNA",
            "MHK",
            "MOH",
            "TAP",
            "MDLZ",
            "MPWR",
            "MNST",
            "MCO",
            "MS",
            "MOS",
            "MSI",
            "MSCI",
            "NDAQ",
            "NTAP",
            "NFLX",
            "NEM",
            "NWSA",
            "NWS",
            "NEE",
            "NKE",
            "NI",
            "NDSN",
            "NSC",
            "NTRS",
            "NOC",
            "NCLH",
            "NRG",
            "NUE",
            "NVDA",
            "NVR",
            "NXPI",
            "ORLY",
            "OXY",
            "ODFL",
            "OMC",
            "ON",
            "OKE",
            "ORCL",
            "OTIS",
            "PCAR",
            "PKG",
            "PANW",
            "PARA",
            "PH",
            "PAYX",
            "PAYC",
            "PYPL",
            "PNR",
            "PEP",
            "PFE",
            "PCG",
            "PM",
            "PSX",
            "PNW",
            "PXD",
            "PNC",
            "POOL",
            "PPG",
            "PPL",
            "PFG",
            "PG",
            "PGR",
            "PLD",
            "PRU",
            "PEG",
            "PTC",
            "PSA",
            "PHM",
            "QRVO",
            "PWR",
            "QCOM",
            "DGX",
            "RL",
            "RJF",
            "RTX",
            "O",
            "REG",
            "REGN",
            "RF",
            "RSG",
            "RMD",
            "RVTY",
            "RHI",
            "ROK",
            "ROL",
            "ROP",
            "ROST",
            "RCL",
            "SPGI",
            "CRM",
            "SBAC",
            "SLB",
            "STX",
            "SEE",
            "SRE",
            "NOW",
            "SHW",
            "SPG",
            "SWKS",
            "SJM",
            "SNA",
            "SEDG",
            "SO",
            "LUV",
            "SWK",
            "SBUX",
            "STT",
            "STLD",
            "STE",
            "SYK",
            "SYF",
            "SNPS",
            "SYY",
            "TMUS",
            "TROW",
            "TTWO",
            "TPR",
            "TRGP",
            "TGT",
            "TEL",
            "TDY",
            "TFX",
            "TER",
            "TSLA",
            "TXN",
            "TXT",
            "TMO",
            "TJX",
            "TSCO",
            "TT",
            "TDG",
            "TRV",
            "TRMB",
            "TFC",
            "TYL",
            "TSN",
            "USB",
            "UDR",
            "ULTA",
            "UNP",
            "UAL",
            "UPS",
            "URI",
            "UNH",
            "UHS",
            "VLO",
            "VTR",
            "VLTO",
            "VRSN",
            "VRSK",
            "VZ",
            "VRTX",
            "VFC",
            "VTRS",
            "VICI",
            "V",
            "VMC",
            "WAB",
            "WBA",
            "WMT",
            "WBD",
            "WM",
            "WAT",
            "WEC",
            "WFC",
            "WELL",
            "WST",
            "WDC",
            "WRK",
            "WY",
            "WHR",
            "WMB",
            "WTW",
            "GWW",
            "WYNN",
            "XEL",
            "XYL",
            "YUM",
            "ZBRA",
            "ZBH",
            "ZION",
            "ZTS",
        ]
        etf_universe = Universe.build_custom_universe("etf_universe", ALL_ETF)
        data = asyncio.run(self._load_universe_async(query, etf_universe))
        return data


if __name__ == "__main__":
    from datetime import datetime
    import time

    start = datetime(2023, 12, 1)
    end = datetime.now()
    query = DataQuery(start=start, end=end)
    data = EtfData()
    time_start = time.time()
    data.load_all(query=query)
    print(f"process time: {time.time() - time_start} seconds!")

# -------------------------------------------------------------------------------------------------------------
# CRYPTO
# -------------------------------------------------------------------------------------------------------------
# class crypto:
#     def __init__(self):
#         self.__service = Tiingo()

#     async
