name: ci pipeline

on:
    push:
        branches: [main,  dev]

    pull_request:
        branches: [main,  dev]

jobs:
    setup-build-test:
        name: setup, install & test
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ['3.8', '3.9', '3.10', '3.11']
        runs-on: ${{ matrix.os }}
        
        steps:
            #----------------------------------------------
            #       check-out repo and set-up python
            #----------------------------------------------
            - name: Check out repository  
              uses: actions/checkout@v3
            - name: setup python ${{ matrix.python-version }} for ${{ matrix.os }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            #----------------------------------------------
            #       install and configure poetry
            #----------------------------------------------
            - name: Install and configure poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true
            
            - name: Install dependencies
              run: poetry install --with=dev --no-interaction --no-root
  
            - name: code quality
              run: make lint && make format
            
            - name: unit tests
              run: make test

